### ISSUE TITLE
Internet Explorer strange behaviour

### ISSUE THREAD

**Issue by DusanSenior** [DataTables/KeyTable#25]
Hello,
please, open https://www.datatables.net/extensions/keytable/examples/initialisation/server-side.html
using Internet Explorer (I have Version 11.0.9600.18161, windows 8.1)

Scenario one:
1) Click at Sales Assistant field f.e. (penultimate row)
2) Press Down key twice (page two is automatically loaded)
3) Regional Director field is selected, but it doesn't have focus (third press of Down key scrolls browser window or does another action at the screen)
In Chrome, FF, Edge(windows 10) it works differently, datatable holds the focus, maybe in Safari as well. I mean it should hold the focus by default in this case.

Scenario two: (reload the page)
1) Click at first row, Accountant f.e. - selected
2) Change page using pager, click page 2 f.e. (no field is selected now)
3) Click at the same possition on the grid (Regional Director field in this example)
4) the field is not selected, but it has a focus, because if you press any arrow key, next field is selected (Down key - Javascript Developer)
It is similar for IE, Chrome, Edge, FF

Thanks for explanation/solution
Best Regards 
Dusan

**Comment by DataTables** [comment]
Hi Dusan,

This is a bug in the current release. If you use the version in this repo, or the [nightly version on the DataTables server](http://datatables.net/download/nightly#KeyTable) the issue should be resolved.

Let me know how you get on with it.

**Comment by DusanSenior** [comment]
It still doesn't work
I already had version from github - jquery.dataTables.js 1.10.11-dev and dataTables.keyTable 2.1.1-dev

**Comment by DataTables** [comment]
Thanks for confirming that. I believe that this has been corrected now :-)

**Comment by DusanSenior** [comment]
I am sorry, but scenario two still doesn't work, when I change page by clicking at pager, previously selected cell still doesn't have class "focus"

**Comment by DataTables** [comment]
Doh - sorry - I misread the second one.

Fixed in f783a3cdde690a9dc6be1c95bbd0fd391c3828a3.

The server-side processing behaviour is now slightly different from client-side in that the focus remains in place when changing page. I may change this for one or other of them in future.

**Comment by DusanSenior** [comment]
Thanks, it is ok now!
